/**
 * Represents the valid statuses a project can have.
 */
export enum ProjectStatus {
  PLANNED = 'PLANNED',
  ACTIVE = 'ACTIVE',
  CLOSED = 'CLOSED'
}

/**
 * Data Transfer Object (DTO) for creating a new project.
 * Excludes the 'id' field as it is generated by the database.
 */
export interface ProjectRequest {
  name: string;
  startDate: string; // Expected format: 'YYYY-MM-DD'
  endDate: string;
  status: ProjectStatus;
  description?: string;
}

/**
 * Represents a full Project entity retrieved from the backend API.
 */
export interface Project {
  id: number;
  name: string;
  startDate: string;
  endDate: string;
  status: ProjectStatus;
  description?: string;
}