spring.application.name=Integrador-SinTeclados

# Configuracion del DataSource (Conexion a PostgreSQL en Docker)
spring.datasource.url=jdbc:postgresql://localhost:5432/sinTecladosDB
spring.datasource.username=sinTeclados
spring.datasource.password=sinTeclados
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracion de JPA (Hibernate)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.postgresql-show=true   

# Configuracion de H2
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
